// auto generated by c2z
const std = @import("std");
const c = @import("c");
//const cpp = @import("cpp");

extern fn _1_ImGui_ImplSDL2_InitForOpenGL_(window: *c.SDL_Window, sdl_gl_context: c.SDL_GLContext) bool;
pub const initForOpenGL = _1_ImGui_ImplSDL2_InitForOpenGL_;

extern fn _1_ImGui_ImplSDL2_InitForVulkan_(window: *c.SDL_Window) bool;
pub const initForVulkan = _1_ImGui_ImplSDL2_InitForVulkan_;

extern fn _1_ImGui_ImplSDL2_InitForD3D_(window: *c.SDL_Window) bool;
pub const initForD3D = _1_ImGui_ImplSDL2_InitForD3D_;

extern fn _1_ImGui_ImplSDL2_InitForMetal_(window: *c.SDL_Window) bool;
pub const initForMetal = _1_ImGui_ImplSDL2_InitForMetal_;

extern fn _1_ImGui_ImplSDL2_InitForSDLRenderer_(window: *c.SDL_Window, renderer: [*c]c.SDL_Renderer) bool;
pub const initForSDLRenderer = _1_ImGui_ImplSDL2_InitForSDLRenderer_;

extern fn _1_ImGui_ImplSDL2_Shutdown_() void;
pub const shutdown = _1_ImGui_ImplSDL2_Shutdown_;

extern fn _1_ImGui_ImplSDL2_NewFrame_() void;
pub const newFrame = _1_ImGui_ImplSDL2_NewFrame_;

extern fn _1_ImGui_ImplSDL2_ProcessEvent_(event: *const c.SDL_Event) bool;
pub const processEvent = _1_ImGui_ImplSDL2_ProcessEvent_;
