// auto generated by c2z
const std = @import("std");
//const cpp = @import("cpp");

const imgui = @import("imgui.zig");

extern fn _1_ImGui_ImplOpenGL3_Init_(glsl_version: [*c]const u8) bool;
pub fn init(
    __opt: struct {
        glsl_version: [*c]const u8 = null,
    },
) bool {
    return _1_ImGui_ImplOpenGL3_Init_(__opt.glsl_version);
}

extern fn _1_ImGui_ImplOpenGL3_Shutdown_() void;
pub const shutdown = _1_ImGui_ImplOpenGL3_Shutdown_;

extern fn _1_ImGui_ImplOpenGL3_NewFrame_() void;
pub const newFrame = _1_ImGui_ImplOpenGL3_NewFrame_;

extern fn _1_ImGui_ImplOpenGL3_RenderDrawData_(draw_data: [*c]imgui.ImDrawData) void;
pub const renderDrawData = _1_ImGui_ImplOpenGL3_RenderDrawData_;

// extern fn _1_ImGui_ImplOpenGL3_CreateFontsTexture_() bool;
// pub const ImGui_ImplOpenGL3_CreateFontsTexture = _1_ImGui_ImplOpenGL3_CreateFontsTexture_;

// extern fn _1_ImGui_ImplOpenGL3_DestroyFontsTexture_() void;
// pub const ImGui_ImplOpenGL3_DestroyFontsTexture = _1_ImGui_ImplOpenGL3_DestroyFontsTexture_;

// extern fn _1_ImGui_ImplOpenGL3_CreateDeviceObjects_() bool;
// pub const ImGui_ImplOpenGL3_CreateDeviceObjects = _1_ImGui_ImplOpenGL3_CreateDeviceObjects_;

// extern fn _1_ImGui_ImplOpenGL3_DestroyDeviceObjects_() void;
// pub const ImGui_ImplOpenGL3_DestroyDeviceObjects = _1_ImGui_ImplOpenGL3_DestroyDeviceObjects_;
